#!/usr/bin/env python3
# archlint (lite) — free MIT tier. GENERATED by `python3 build.py --lite`
# from the full archlint.py; do not edit by hand. The Pro tier (cycle
# detection, hard-block severity, public-API leakage, init, baseline,
# report, graph, multi-harness, Java/C#, SARIF, one-command install) lives
# at https://github.com/MKanhan/archlint.
"""
archlint — architectural drift detector for Claude Code.

A single-file hook that:
  1. Reads an architecture blueprint from CLAUDE.md or ARCHITECTURE.md.
  2. On every Write/Edit/MultiEdit, checks the edited file against the
     declared layer rules (deterministic, AST/regex-based).
  3. On Stop (end-of-turn), emits a checkpoint summary so the agent
     can self-correct before declaring done.

Stdlib only. No network. No LLM calls in the hot path.

Hook input arrives on stdin as JSON; output goes to stdout as JSON.
Exit code 0 = continue. Exit code 2 = block (used sparingly; the
JSON `decision: block` channel is preferred and gives a reason).

Install:
    Place this file at  .claude/hooks/archlint.py  (chmod +x)
    Add to .claude/settings.json:

    {
      "hooks": {
        "PostToolUse": [{
          "matcher": "Write|Edit|MultiEdit",
          "hooks": [{
            "type": "command",
            "command": "python3 $CLAUDE_PROJECT_DIR/.claude/hooks/archlint.py post"
          }]
        }],
        "Stop": [{
          "hooks": [{
            "type": "command",
            "command": "python3 $CLAUDE_PROJECT_DIR/.claude/hooks/archlint.py stop"
          }]
        }]
      }
    }

Environment:
    ARCHLINT_MODE        lenient (default) | strict
    ARCHLINT_BLUEPRINT   path override; defaults to CLAUDE.md, AGENTS.md, ARCHITECTURE.md, SPEC.md, ROADMAP.md (first found)
    ARCHLINT_QUIET       1 to silence non-blocking output
"""

from __future__ import annotations

import ast
import fnmatch
import functools
import json
import os
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Iterator

__version__ = "0.15.0"

# ---------------------------------------------------------------------------
# Paths & state
# ---------------------------------------------------------------------------

PROJECT_DIR = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()).resolve()
STATE_DIR = PROJECT_DIR / ".archlint"
TURN_STATE = STATE_DIR / "turn.json"  # accumulates findings within a turn
DRIFT_LOG = STATE_DIR / "drift.jsonl"  # structured drift history (read by `report`)
BASELINE = STATE_DIR / "baseline.json"  # accepted findings (commit this one)

BLUEPRINT_CANDIDATES = ("CLAUDE.md", "AGENTS.md", "ARCHITECTURE.md", "SPEC.md", "ROADMAP.md")
MODE = os.environ.get("ARCHLINT_MODE", "lenient").lower()
QUIET = os.environ.get("ARCHLINT_QUIET") == "1"

# ---------------------------------------------------------------------------
# Blueprint parsing
# ---------------------------------------------------------------------------


@dataclass
class Rules:
    layers: dict[str, list[str]] = field(default_factory=dict)  # name -> globs
    allowed: set[tuple[str, str]] = field(default_factory=set)  # (src, dst)
    forbidden: list[tuple[str, str, bool]] = field(default_factory=list)  # (src, dst, hard)
    raw_block: str = ""
    errors: list[str] = field(default_factory=list)  # unparseable blueprint lines
    max_file_lines: int = 500
    detect_cycles: bool = True

    def layer_of(self, rel_path: str) -> str | None:
        """Return the layer name a path belongs to, or None."""
        # Normalize to forward slashes for glob matching
        p = rel_path.replace(os.sep, "/")
        for name, globs in self.layers.items():
            for g in globs:
                if fnmatch.fnmatch(p, g):
                    return name
        return None


# Dedicated-first: a purpose-built ARCHITECTURE.md that actually declares an
# archlint block wins over a CLAUDE.md/AGENTS.md (which exist for other reasons).
_BLUEPRINT_PRIORITY = ("ARCHITECTURE.md", "CLAUDE.md", "AGENTS.md", "SPEC.md", "ROADMAP.md")


def _has_archlint_block(path: Path) -> bool:
    """A host counts as a blueprint only if its archlint block declares at least one
    rule (a layer or a forbid). An empty or comment-only example fence — e.g. docs that
    merely show the syntax — is not a blueprint and must not shadow the real host."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    rules = parse_blueprint(text)
    return bool(rules.layers or rules.forbidden)


def find_blueprint() -> Path | None:
    override = os.environ.get("ARCHLINT_BLUEPRINT")
    if override:
        path = Path(override)
        if not path.is_absolute():
            path = PROJECT_DIR / path
        return path if path.exists() else None
    # Content-aware: pick the first host (dedicated-first) that actually carries a
    # rule-bearing block, so a dedicated ARCHITECTURE.md is no longer shadowed by a
    # block-less CLAUDE.md.
    hosts = [PROJECT_DIR / n for n in _BLUEPRINT_PRIORITY
             if (PROJECT_DIR / n).exists() and _has_archlint_block(PROJECT_DIR / n)]
    if hosts:
        if len(hosts) > 1:
            # Never silently pick the wrong host: surface the ambiguity.
            others = ", ".join(h.name for h in hosts[1:])
            msg = (f"multiple files declare an archlint block ({hosts[0].name} + {others}); "
                   f"using {hosts[0].name} — keep the blueprint in one file")
            if msg not in RESOLVER_WARNINGS:
                RESOLVER_WARNINGS.append(msg)
        return hosts[0]
    # No block anywhere: fall back to the first existing candidate (CLAUDE.md by
    # convention) so blueprint diagnostics / init still have a place to attach.
    for name in BLUEPRINT_CANDIDATES:
        path = PROJECT_DIR / name
        if path.exists():
            return path
    return None


# Match a fenced block: ```archlint ... ```
_FENCE_RE = re.compile(r"```archlint\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)


def parse_blueprint(text: str) -> Rules:
    """Extract rules from a markdown blueprint.

    The blueprint must contain a fenced code block with language `archlint`.
    Grammar (one statement per line; # starts a comment):

        layer <name> = <glob>, <glob>, ...
        <name> -> <name>               (allowed dependency)
        forbid <name|glob> -> <name|glob>
        set max-file-lines <N>

    Lines matching no statement are collected in `rules.errors` — a typo'd
    rule must never be silently inert.
    """
    rules = Rules()
    match = _FENCE_RE.search(text)
    if not match:
        return rules
    rules.raw_block = match.group(1)

    for lineno, raw_line in enumerate(rules.raw_block.splitlines(), start=1):
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue

        # layer NAME = glob, glob
        m = re.match(r"^layer\s+([A-Za-z0-9_\-]+)\s*=\s*(.+)$", line)
        if m:
            name = m.group(1)
            globs = [g.strip() for g in m.group(2).split(",") if g.strip()]
            rules.layers[name] = globs
            continue

        # forbid X -> Y  (plain prohibition; respects ARCHLINT_MODE)
        m = re.match(r"^forbid\s+(\S+)\s*->\s*(\S+)$", line)
        if m:
            rules.forbidden.append((m.group(1), m.group(2), False))
            continue

        # X -> Y  (allowed dependency)
        m = re.match(r"^(\S+)\s*->\s*(\S+)$", line)
        if m:
            rules.allowed.add((m.group(1), m.group(2)))
            continue

        # set max-file-lines N
        m = re.match(r"^set\s+max-file-lines\s+(\d+)$", line)
        if m:
            rules.max_file_lines = int(m.group(1))
            continue

        # set detect-cycles on|off
        m = re.match(r"^set\s+detect-cycles\s+(on|off)$", line)
        if m:
            rules.detect_cycles = m.group(1) == "on"
            continue

        rules.errors.append(f"line {lineno}: unrecognized statement: {line!r}")

    return rules


# ---------------------------------------------------------------------------
# Import extraction
# ---------------------------------------------------------------------------


_JS_SUFFIXES = {".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"}


def extract_imports(file_path: Path) -> list[str]:
    """Return raw module strings imported by `file_path`. Language-aware-ish."""
    suffix = file_path.suffix.lower()
    try:
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeDecodeError):
        return []

    if suffix == ".py":
        return _imports_python(text)
    if suffix in _JS_SUFFIXES:
        return _imports_js(text)
    if suffix == ".go":
        return _imports_go(text)
    if suffix in {".rs"}:
        return _imports_rust(text)
    return []


def _imports_python(text: str) -> list[str]:
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return []
    out: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            out.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                # Preserve relative-import dots if present
                prefix = "." * (node.level or 0)
                out.append(prefix + node.module)
            elif node.level:
                out.append("." * node.level)
    return out


_JS_IMPORT_RE = re.compile(
    r"""(?mx)
    ^\s*(?:
        import\s+(?:[^'"`;]+?\s+from\s+)?['"]([^'"]+)['"]
      | (?:const|let|var)\s+[^=;]+?=\s*require\(\s*['"]([^'"]+)['"]\s*\)
      | export\s+(?:\*|\{[^}]*\})\s+from\s+['"]([^'"]+)['"]
    )
    """
)


def _imports_js(text: str) -> list[str]:
    out: list[str] = []
    for m in _JS_IMPORT_RE.finditer(text):
        spec = m.group(1) or m.group(2) or m.group(3)
        if spec:
            out.append(spec)
    return out


_GO_IMPORT_BLOCK_RE = re.compile(r"import\s*\(([^)]*)\)", re.DOTALL)
_GO_IMPORT_SINGLE_RE = re.compile(r'import\s+"([^"]+)"')
_GO_QUOTED_RE = re.compile(r'"([^"]+)"')


def _imports_go(text: str) -> list[str]:
    out: list[str] = []
    for block in _GO_IMPORT_BLOCK_RE.findall(text):
        out.extend(_GO_QUOTED_RE.findall(block))
    out.extend(_GO_IMPORT_SINGLE_RE.findall(text))
    return out


_RUST_USE_RE = re.compile(r"^\s*(?:pub\s+)?use\s+([^;]+);", re.MULTILINE)
_RUST_BRACE_RE = re.compile(r"^(.*?)::\{(.*)\}$", re.DOTALL)


def _imports_rust(text: str) -> list[str]:
    out: list[str] = []
    for m in _RUST_USE_RE.finditer(text):
        stmt = m.group(1).strip()
        # Expand one level of braced groups: a::{b, c::d} -> a::b, a::c::d
        brace = _RUST_BRACE_RE.match(stmt)
        if brace:
            prefix = brace.group(1).strip()
            specs = [f"{prefix}::{p.strip()}" for p in brace.group(2).split(",") if p.strip()]
        else:
            specs = [stmt]
        for spec in specs:
            spec = re.sub(r"\s+as\s+\w+$", "", spec)  # strip `as` renames
            spec = re.sub(r"::\*$", "", spec)         # strip glob imports
            if spec:
                out.append(spec)
    return out




# ---------------------------------------------------------------------------
# Import → layer resolution
# ---------------------------------------------------------------------------

# Non-fatal problems found while resolving (e.g. unparseable tsconfig).
# Surfaced through the same diagnostics channel as blueprint errors.
RESOLVER_WARNINGS: list[str] = []


def _strip_jsonc(text: str) -> str:
    """Minimal JSONC -> JSON: tsconfig/jsconfig routinely carry // and /* */
    comments and trailing commas. A character scanner (not a regex) so that
    comment markers, `*/`, and commas *inside* string literals are preserved —
    e.g. a `"@/*"` paths alias or an `"https://..."` URL must not be eaten."""
    out: list[str] = []
    i, n = 0, len(text)
    in_str = False
    pending_comma = -1  # index in `out` of a comma awaiting its next real token
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            if c == "\\" and i + 1 < n:      # keep the escaped char verbatim
                out.append(text[i + 1])
                i += 2
                continue
            if c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            pending_comma = -1               # a value follows -> comma was real
            out.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "/":   # // line comment
            i += 2
            while i < n and text[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "*":   # /* block comment */
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        if c == ",":
            pending_comma = len(out)
            out.append(c)
            i += 1
            continue
        if c in "}]" and pending_comma != -1:               # drop trailing comma
            out[pending_comma] = ""
            pending_comma = -1
            out.append(c)
            i += 1
            continue
        if not c.isspace():                  # any other token cancels the comma
            pending_comma = -1
        out.append(c)
        i += 1
    return "".join(out)


@functools.lru_cache(maxsize=None)
def _ts_config() -> tuple | None:
    """(base_dir, ((pattern, (target, ...)), ...)) from tsconfig/jsconfig, or None."""
    for name in ("tsconfig.json", "jsconfig.json"):
        cfg_path = PROJECT_DIR / name
        if not cfg_path.exists():
            continue
        try:
            # utf-8-sig strips a leading BOM (common on Windows-authored tsconfig)
            # so json.loads doesn't choke and disable aliases.
            data = json.loads(_strip_jsonc(cfg_path.read_text(encoding="utf-8-sig", errors="replace")))
        except json.JSONDecodeError as e:
            RESOLVER_WARNINGS.append(f"{name} could not be parsed ({e}) — path aliases disabled")
            return None
        opts = data.get("compilerOptions", {}) or {}
        base = (PROJECT_DIR / opts.get("baseUrl", ".")).resolve()
        paths = opts.get("paths", {}) or {}
        entries = tuple(
            (pat, tuple(t for t in targets if isinstance(t, str)))
            for pat, targets in paths.items()
            if isinstance(pat, str) and isinstance(targets, list)
        )
        return (base, entries)
    return None


def _resolve_ts_alias(spec: str) -> Path | None:
    """Resolve a non-relative JS/TS import via tsconfig baseUrl/paths."""
    cfg = _ts_config()
    if cfg is None:
        return None
    base, entries = cfg
    # Exact patterns first, then single-* wildcards by longest prefix
    # (approximates tsc's specificity ordering).
    for pat, targets in entries:
        if "*" not in pat and spec == pat:
            for target in targets:
                hit = _first_existing_module((base / target).resolve())
                if hit:
                    return hit
    wildcards = sorted(
        (e for e in entries if e[0].count("*") == 1),
        key=lambda e: len(e[0].split("*")[0]),
        reverse=True,
    )
    for pat, targets in wildcards:
        prefix, suffix = pat.split("*")
        if spec.startswith(prefix) and spec.endswith(suffix) and len(spec) >= len(prefix) + len(suffix):
            star = spec[len(prefix):len(spec) - len(suffix)] if suffix else spec[len(prefix):]
            for target in targets:
                hit = _first_existing_module((base / target.replace("*", star)).resolve())
                if hit:
                    return hit
    # Plain baseUrl-relative import (the PROJECT_DIR case is covered by the
    # generic root-relative fallback in resolve_import_to_path).
    if base != PROJECT_DIR:
        return _first_existing_module((base / spec).resolve())
    return None


@functools.lru_cache(maxsize=None)
def _go_module() -> str | None:
    gomod = PROJECT_DIR / "go.mod"
    if not gomod.exists():
        return None
    m = re.search(r"(?m)^module\s+(\S+)", gomod.read_text(encoding="utf-8", errors="replace"))
    return m.group(1) if m else None


def _resolve_go_package(spec: str) -> Path | None:
    """Map a module-prefixed Go import to a representative file in the
    package directory (any .go file fixes the layer; dirs themselves
    don't match `pkg/**` globs)."""
    module = _go_module()
    if not module:
        return None
    if spec == module:
        rel = ""
    elif spec.startswith(module + "/"):
        rel = spec[len(module) + 1:]
    else:
        return None
    pkg_dir = (PROJECT_DIR / rel) if rel else PROJECT_DIR
    if pkg_dir.is_dir():
        go_files = sorted(p for p in pkg_dir.iterdir() if p.suffix == ".go")
        if go_files:
            return go_files[0]
    return None


def _rust_crate_root(importer: Path) -> Path:
    for parent in importer.parents:
        if parent.name == "src":
            return parent
        if parent == PROJECT_DIR:
            break
    return PROJECT_DIR / "src"


def _resolve_rust_path(base: Path, segments: list[str]) -> Path | None:
    """Probe base/<segs>.rs then base/<segs>/mod.rs; retry once without the
    last segment (usually an item — fn/struct/`self` — not a module)."""
    attempts = [segments] + ([segments[:-1]] if segments else [])
    for segs in attempts:
        if not segs:
            for name in ("mod.rs", "lib.rs", "main.rs"):
                cand = base / name
                if cand.is_file():
                    return cand
            continue
        stem = base.joinpath(*segs)
        cand = stem.parent / (stem.name + ".rs")
        if cand.is_file():
            return cand
        cand = stem / "mod.rs"
        if cand.is_file():
            return cand
    return None




def resolve_import_to_path(importer: Path, spec: str) -> Path | None:
    """Best-effort: map an import spec to a project-relative path.

    Resolves local-looking imports: relative paths, tsconfig aliases /
    baseUrl, Go module-prefixed packages, Rust crate/self/super paths, and
    Python dotted paths (project root or src/ layout). External package
    imports return None and are ignored by layer rules.
    """
    # Python relative import (".pkg" or "..pkg"). No slashes — those are JS/TS.
    if spec.startswith(".") and "/" not in spec:
        # Walk up `level` dirs from the importer
        level = len(spec) - len(spec.lstrip("."))
        rest = spec[level:].replace(".", "/")
        base = importer.parent
        for _ in range(level - 1):
            base = base.parent
        candidate = (base / rest) if rest else base
        return _first_existing_module(candidate)

    # JS/TS relative
    if spec.startswith("./") or spec.startswith("../"):
        candidate = (importer.parent / spec).resolve()
        return _first_existing_module(candidate)

    # Rust crate-rooted / module-relative paths
    if importer.suffix == ".rs" and re.match(r"^(crate|self|super)(::|$)", spec):
        segments = [s for s in spec.split("::") if s]
        head = segments[0]
        if head == "crate":
            base = _rust_crate_root(importer)
            segments = segments[1:]
        elif head == "self":
            base = importer.parent
            segments = segments[1:]
        else:  # one or more leading `super`
            base = importer.parent
            while segments and segments[0] == "super":
                base = base.parent
                segments = segments[1:]
        return _resolve_rust_path(base, segments)

    # JS/TS path alias / baseUrl (tsconfig.json or jsconfig.json)
    if importer.suffix.lower() in _JS_SUFFIXES:
        resolved = _resolve_ts_alias(spec)
        if resolved:
            return resolved

    # Go module-prefixed package import (go.mod)
    if importer.suffix == ".go":
        resolved = _resolve_go_package(spec)
        if resolved:
            return resolved

    # Try treating as project-root-relative (e.g. "src/services/user")

    candidate = PROJECT_DIR / spec
    resolved = _first_existing_module(candidate)
    if resolved:
        return resolved

    # Python dotted path — try project root, then src/ layout
    if re.fullmatch(r"[A-Za-z0-9_.]+", spec):
        rel = spec.replace(".", os.sep)
        for root in (PROJECT_DIR, PROJECT_DIR / "src"):
            resolved = _first_existing_module(root / rel)
            if resolved:
                return resolved

    return None


_MODULE_SUFFIXES = (
    ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".go", ".rs",
)


def _first_existing_module(base: Path) -> Path | None:
    if base.is_file():
        return base
    # Try adding each known extension. `with_suffix` only works if `base`
    # already has a suffix to swap; for suffix-less imports like
    # "../repos/user_repo" we need to append.
    for suf in _MODULE_SUFFIXES:
        cand = base.parent / (base.name + suf)
        if cand.is_file():
            return cand
        # Also handle the case where base does have a dotted suffix already
        # (e.g. a relative import resolved into a path with dots).
        if base.suffix:
            swapped = base.with_suffix(suf)
            if swapped.is_file():
                return swapped
    # index.* in a directory
    if base.is_dir():
        for suf in _MODULE_SUFFIXES:
            cand = base / f"index{suf}"
            if cand.is_file():
                return cand
        for suf in _MODULE_SUFFIXES:
            cand = base / f"__init__{suf}"
            if cand.is_file():
                return cand
    return None


# ---------------------------------------------------------------------------
# Rule checking
# ---------------------------------------------------------------------------


@dataclass
class Finding:
    kind: str        # "forbidden" | "undeclared" | "smell" | "cycle" | "leakage"
    file: str        # relative path
    detail: str      # human-readable
    suggestion: str = ""
    dst: str = ""    # target rel path (or cycle members); "" for file smells
    severity: str = "soft"  # "soft" (respects MODE) | "hard" (always blocks)
    rule: str = ""   # "src -> dst" for dependency findings; used by `report`
    line: int = 0    # 1-based line of the offending import; 0 = file-level (SARIF region)


def _matches_target(target: str, layer: str | None, rel_path: str) -> bool:
    """A forbid target can be a layer name OR a glob over paths."""
    if layer is not None and target == layer:
        return True
    if any(c in target for c in "*?["):
        return fnmatch.fnmatch(rel_path.replace(os.sep, "/"), target)
    return False




def check_file(file_path: Path, rules: Rules) -> list[Finding]:
    """Check a single edited file against the rules."""
    findings: list[Finding] = []
    try:
        rel = file_path.resolve().relative_to(PROJECT_DIR)
    except ValueError:
        return findings  # outside the project; skip
    rel_str = str(rel)

    src_layer = rules.layer_of(rel_str)
    imports = extract_imports(file_path)

    for spec in imports:
        target_path = resolve_import_to_path(file_path, spec)
        if target_path is None:
            continue  # external dependency
        try:
            target_rel = str(target_path.resolve().relative_to(PROJECT_DIR))
        except ValueError:
            continue
        dst_layer = rules.layer_of(target_rel)
        forbidden_hit = False

        # 1. Forbidden rules (explicit blacklist)
        for src_pat, dst_pat, hard in rules.forbidden:
            src_match = (
                src_pat == "*"
                or (src_layer is not None and src_pat == src_layer)
                or _matches_target(src_pat, src_layer, rel_str)
            )
            dst_match = (
                dst_pat == "*"
                or (dst_layer is not None and dst_pat == dst_layer)
                or _matches_target(dst_pat, dst_layer, target_rel)
            )
            if src_match and dst_match:
                forbidden_hit = True
                findings.append(Finding(
                    kind="forbidden",
                    file=rel_str,
                    detail=f"{rel_str} imports {target_rel} (forbidden: {src_pat} -> {dst_pat})",
                    suggestion=_suggest_for_forbidden(src_pat, dst_pat, rules),
                    dst=target_rel,
                    severity="hard" if hard else "soft",
                    rule=f"{src_pat} -> {dst_pat}",
                ))

        # 2. Undeclared cross-layer dependency — only if not already flagged above.
        if forbidden_hit:
            continue
        cross_layer = (
            src_layer is not None
            and dst_layer is not None
            and src_layer != dst_layer
        )
        if cross_layer and (src_layer, dst_layer) not in rules.allowed:
            # Only flag if there ARE any allowed edges from this src — otherwise
            # the layer has no declared outgoing rules and we stay quiet.
            if any(s == src_layer for s, _ in rules.allowed):
                findings.append(Finding(
                    kind="undeclared",
                    file=rel_str,
                    detail=(
                        f"{rel_str} ({src_layer}) imports {target_rel} ({dst_layer}) "
                        f"but `{src_layer} -> {dst_layer}` is not declared"
                    ),
                    suggestion=(
                        f"Either route through an allowed layer, or add "
                        f"`{src_layer} -> {dst_layer}` to the blueprint if intentional."
                    ),
                    dst=target_rel,
                    rule=f"{src_layer} -> {dst_layer}",
                ))
                continue


    # 4. File smell: oversized source files. Only code — a long log or markdown
    # doc is not a "missing layer", and the hook checks whatever file was edited.
    try:
        line_count = sum(1 for _ in file_path.open("r", encoding="utf-8", errors="replace"))
    except OSError:
        line_count = 0
    if file_path.suffix.lower() in _SCAN_EXTS and line_count > rules.max_file_lines:
        findings.append(Finding(
            kind="smell",
            file=rel_str,
            detail=f"{rel_str} is {line_count} lines — consider splitting",
            suggestion="Large files often indicate a missing layer or mixed concerns.",
        ))

    return findings


def _suggest_for_forbidden(src_pat: str, dst_pat: str, rules: Rules) -> str:
    """Suggest a known-good route: src -> ? -> dst, one hop."""
    for mid in rules.layers:
        if (src_pat, mid) in rules.allowed and (mid, dst_pat) in rules.allowed:
            return f"Route through `{mid}` instead: {src_pat} -> {mid} -> {dst_pat}."
    return f"This crosses a forbidden boundary. Find an allowed path from `{src_pat}`."


# ---------------------------------------------------------------------------
# Hook event handlers
# ---------------------------------------------------------------------------


def _load_turn_state() -> dict:
    if TURN_STATE.exists():
        try:
            return json.loads(TURN_STATE.read_text(encoding="utf-8", errors="replace"))
        except json.JSONDecodeError:
            return {"findings": [], "started": time.time()}
    return {"findings": [], "started": time.time()}


def _save_turn_state(state: dict) -> None:
    STATE_DIR.mkdir(exist_ok=True)
    TURN_STATE.write_text(json.dumps(state))


def fingerprint(f: Finding) -> str:
    """Stable identity for a finding: survives line-count and message changes."""
    return "|".join((
        f.kind,
        f.file.replace(os.sep, "/"),
        f.dst.replace(os.sep, "/"),
    ))


def _load_baseline() -> set[str]:
    if BASELINE.exists():
        try:
            data = json.loads(BASELINE.read_text(encoding="utf-8", errors="replace"))
            return set(data.get("fingerprints", []))
        except (json.JSONDecodeError, OSError):
            return set()
    return set()


def _diagnostics_message(rules: Rules) -> str:
    lines: list[str] = []
    if rules.errors:
        lines.append("archlint: blueprint diagnostics — these lines were ignored:")
        lines.extend(f"  - {e}" for e in rules.errors)
    if RESOLVER_WARNINGS:
        if lines:
            lines.append("")
        lines.append("archlint: resolver warnings:")
        lines.extend(f"  - {w}" for w in RESOLVER_WARNINGS)
    return "\n".join(lines)


def _emit(payload: dict) -> None:
    """Write hook output JSON and exit."""
    sys.stdout.write(json.dumps(payload))
    sys.stdout.flush()
    sys.exit(0)


def _should_block(findings: Iterable[Finding]) -> bool:
    """Block when running strict, or whenever a hard (always-block) rule is hit."""
    return MODE == "strict" or any(f.severity == "hard" for f in findings)


def _log_drift(turn_id, event: str, findings: Iterable[Finding]) -> None:
    """Append structured drift events for `archlint report` to read."""
    findings = list(findings)
    if not findings:
        return
    STATE_DIR.mkdir(exist_ok=True)
    with DRIFT_LOG.open("a") as log:
        for f in findings:
            log.write(json.dumps({
                "ts": int(time.time()),
                "turn": turn_id,
                "event": event,
                "kind": f.kind,
                "file": f.file,
                "fp": fingerprint(f),
                "rule": f.rule,
            }) + "\n")




# ---------------------------------------------------------------------------
# Harness adapters — same engine, harness-specific hook I/O. The core
# (detection, baseline, turn state, drift log, re-verify, _should_block) is
# common; only event parsing and the emitted payload differ per harness.
# ---------------------------------------------------------------------------


class _ClaudeAdapter:
    """Claude Code: PostToolUse/Stop, can block or inject additionalContext."""

    @staticmethod
    def edited(event: dict) -> list[str]:
        ti = event.get("tool_input", {}) or {}
        out: list[str] = []
        if "file_path" in ti:
            out.append(ti["file_path"])
        elif "edits" in ti and isinstance(ti["edits"], list):
            for e in ti["edits"]:
                if isinstance(e, dict) and "file_path" in e:
                    out.append(e["file_path"])
        return out

    @staticmethod
    def stop_loop(event: dict) -> bool:
        return bool(event.get("stop_hook_active"))

    @staticmethod
    def emit_post(message: str, block: bool) -> dict:
        if block:
            return {"decision": "block", "reason": message}
        return {"hookSpecificOutput": {"hookEventName": "PostToolUse", "additionalContext": message}}

    @staticmethod
    def emit_stop(message: str, block: bool) -> dict:
        if block:
            return {"decision": "block", "reason": message + "\n\nResolve these before declaring done."}
        return {"hookSpecificOutput": {"hookEventName": "Stop", "additionalContext": message}}






def handle_post_tool_use(event: dict, rules: Rules, adapter=_ClaudeAdapter) -> None:
    """Per-edit check. Surface findings via the harness adapter (additionalContext
    or block on Claude; observe-only on Cursor)."""
    edited = adapter.edited(event)

    all_findings: list[Finding] = []
    for fp in edited:
        path = Path(fp)
        if not path.is_absolute():
            path = PROJECT_DIR / path
        if not path.exists():
            continue
        all_findings.extend(check_file(path, rules))

    baseline = _load_baseline()
    all_findings = [f for f in all_findings if fingerprint(f) not in baseline]

    state = _load_turn_state()
    diagnostics = "" if state.get("diag_emitted") else _diagnostics_message(rules)

    if not all_findings:
        if diagnostics and not QUIET:
            state["diag_emitted"] = True
            _save_turn_state(state)
            _emit(adapter.emit_post(diagnostics, False))
        _emit({})

    # Persist findings for the Stop checkpoint. `diag_emitted` is set only when the
    # diagnostics are actually shown (below) — so under QUIET a blueprint typo isn't
    # silently consumed; it resurfaces on a later edit or at the checkpoint.
    for f in all_findings:
        state["findings"].append({
            "kind": f.kind, "file": f.file,
            "detail": f.detail, "suggestion": f.suggestion, "dst": f.dst,
            "severity": f.severity, "rule": f.rule,
        })

    _log_drift(state.get("started"), "detected", all_findings)

    block = _should_block(all_findings)
    if QUIET and not block:
        # ARCHLINT_QUIET: detection is still recorded (turn state + drift log); only
        # the non-blocking feedback is silenced. Hard/strict blocks are never suppressed.
        _save_turn_state(state)
        _emit({})

    if diagnostics:
        state["diag_emitted"] = True
    _save_turn_state(state)

    message = _format_findings(all_findings, header="archlint: drift detected on this edit")
    if diagnostics:
        message = diagnostics + "\n\n" + message

    _emit(adapter.emit_post(message, block))


def handle_stop(event: dict, rules: Rules, adapter=_ClaudeAdapter) -> None:
    """End-of-turn checkpoint: aggregate, re-verify, and surface via the adapter."""
    # Prevent loops: if we're already re-firing because of our own message, stop.
    if adapter.stop_loop(event):
        TURN_STATE.unlink(missing_ok=True)
        _emit({})

    state = _load_turn_state()
    turn_id = state.get("started")
    findings_raw = state.get("findings", [])
    TURN_STATE.unlink(missing_ok=True)

    # Re-verify: only nag about drift that is STILL present. Drift introduced and
    # then fixed within the turn shouldn't resurface — and this keeps the
    # self-correction metric honest.
    baseline = _load_baseline()
    accumulated: dict[str, Finding] = {}
    for raw in findings_raw:
        f = Finding(**raw)
        accumulated.setdefault(fingerprint(f), f)
    current_fps: set[str] = set()
    for rel in {f.file for f in accumulated.values() if f.file}:
        path = PROJECT_DIR / rel
        if path.exists():
            current_fps.update(fingerprint(cf) for cf in check_file(path, rules))
    unresolved = [
        f for fp, f in accumulated.items()
        if fp in current_fps and fp not in baseline
    ]
    _log_drift(turn_id, "unresolved", unresolved)

    findings = unresolved
    if not findings:
        _emit({})

    block = _should_block(findings)
    if QUIET and not block:
        # ARCHLINT_QUIET: silence the non-blocking checkpoint nag (the unresolved
        # drift was already logged above for `report`); a hard/strict stop stands.
        _emit({})
    message = _format_findings(findings, header="archlint checkpoint: unresolved drift before stopping")
    _emit(adapter.emit_stop(message, block))


def _format_findings(findings: Iterable[Finding], header: str) -> str:
    lines = [header, ""]
    by_kind: dict[str, list[Finding]] = {}
    for f in findings:
        by_kind.setdefault(f.kind, []).append(f)

    labels = {
        "forbidden": "Forbidden dependencies",
        "undeclared": "Undeclared cross-layer dependencies",
        "cycle": "Layer cycles",
        "leakage": "Public-API leakage",
        "smell": "Code smells",
    }
    for kind in ("forbidden", "undeclared", "cycle", "leakage", "smell"):
        items = by_kind.get(kind)
        if not items:
            continue
        lines.append(f"{labels[kind]}:")
        for f in items:
            mark = " [hard — must fix]" if f.severity == "hard" else ""
            lines.append(f"  - {f.detail}{mark}")
            if f.suggestion:
                lines.append(f"    → {f.suggestion}")
        lines.append("")
    return "\n".join(lines).rstrip()


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------


def main() -> None:
    if len(sys.argv) < 2:
        usage = "usage: archlint.py {post|stop|check|--version}\n"
        sys.stderr.write(usage)
        sys.exit(1)
    action = sys.argv[1]

    # Commands that neither consume nor require a blueprint via the hook guards —
    # handle before the no-op/blueprint-required logic below.
    if action in ("--version", "-V", "version"):
        print(f"archlint {__version__}")
        return

    blueprint = find_blueprint()
    if blueprint is None:
        # No blueprint — silently no-op. archlint should never break a workflow.
        _emit({})

    rules = parse_blueprint(blueprint.read_text(encoding="utf-8", errors="replace"))
    if not rules.layers and not rules.errors:
        # Blueprint exists but no archlint block — also a no-op.
        _emit({})

    warn_actions = ("check",)
    if action in warn_actions:
        for err in rules.errors:
            sys.stderr.write(f"archlint: blueprint warning: {err}\n")

    if action == "post":
        adapter = _ClaudeAdapter
        try:
            event = json.load(sys.stdin)
        except json.JSONDecodeError:
            event = {}
        handle_post_tool_use(event, rules, adapter)
    elif action == "stop":
        adapter = _ClaudeAdapter
        try:
            event = json.load(sys.stdin)
        except json.JSONDecodeError:
            event = {}
        handle_stop(event, rules, adapter)
    elif action == "check":
        # Manual one-shot: scan all tracked files — a pre-commit hook or CI step.
        fmt = "text"
        run_full_scan(rules, fmt)
    else:
        sys.stderr.write(f"unknown action: {action}\n")
        sys.exit(1)


_SCAN_EXTS = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".go", ".rs",
}
_SCAN_SKIP_DIRS = {".git", "node_modules", ".venv", "venv", "dist", "build", ".archlint",
                   "__pycache__", ".claude", ".cursor"}


def _iter_source_files(root: Path = PROJECT_DIR) -> Iterator[Path]:
    """Yield every source file under `root`, skipping vendor/build dirs."""
    for dirpath, dirs, files in os.walk(root):
        dirs[:] = [d for d in dirs if d not in _SCAN_SKIP_DIRS]
        for name in files:
            if Path(name).suffix.lower() in _SCAN_EXTS:
                yield Path(dirpath) / name


def scan_project(rules: Rules) -> list[Finding]:
    """Scan every source file in the project."""
    all_findings: list[Finding] = []
    for path in _iter_source_files():
        all_findings.extend(check_file(path, rules))
    return all_findings


def _print_resolver_warnings() -> None:
    for w in RESOLVER_WARNINGS:
        sys.stderr.write(f"archlint: resolver warning: {w}\n")




def run_full_scan(rules: Rules, fmt: str = "text") -> None:
    """CLI mode: archlint check — report non-baselined drift.

    Prints the human report and exits 1 on drift — the pre-commit / CI
    fail-fast path."""
    baseline = _load_baseline()
    raw = scan_project(rules)
    findings = [f for f in raw if fingerprint(f) not in baseline]
    _print_resolver_warnings()
    if not findings:
        print("archlint: no drift detected.")
        sys.exit(0)
    print(_format_findings(findings, header=f"archlint: {len(findings)} finding(s)"))
    sys.exit(1)












if __name__ == "__main__":
    main()
